init:
  - git config --global core.autocrlf true

version: '{branch}-{build}'

image: Visual Studio 2017

skip_tags: true

configuration: Release
platform: Any CPU

shallow_clone: true

environment:
  COVERALLS_REPO_TOKEN:
    secure: TuzfJo1wRIIoC/i5Oxa1tifRWgQ60loT0GbPjuircCeW5sH5uC714YWVJ02EXnVG

before_build:
- cmd: >-
    _build\version.bat
    
    _build\restore.bat Utilitron
    
build_script:
- cmd: _build\build.bat Utilitron

test_script:
- cmd: _build\test.bat Utilitron

after_test:
- cmd: _build\package.bat Utilitron

artifacts:
- path: '*.nupkg'
  name: Nuget Package

deploy:
- provider: NuGet
  api_key:
    secure: P2oh37pn3l7Tp9qTP87aOB0GFxg8WnlFyV8n3p1eqMS5aUVur1Yg3xQ2inbIDOCr
  skip_symbols: false
  on:
    branch: master
