init:
  - git config --global core.autocrlf true

version: '{branch}-{build}'

skip_tags: true

configuration: Release
platform: Any CPU

shallow_clone: true

environment:
  COVERALLS_REPO_TOKEN:
    secure: TuzfJo1wRIIoC/i5Oxa1tifRWgQ60loT0GbPjuircCeW5sH5uC714YWVJ02EXnVG

build:
  project: Utilitron.sln
  verbosity: minimal

after_test:
- cmd: >-
    test.bat
    
    nuget.bat

artifacts:
- path: '*.nupkg'
  name: Nuget Package
